In [2]:
%pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/3c/a1/accf6d4f0c80c5d9ba9735d6b1550e444180599f34dec69ca01360f717ad/numpy-2.5.3-cp312-cp312-win_amd64.whl.metadata
  Using cached numpy-2.5.3-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----------------------


[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy 

In [4]:
vector = [ 1 , 2 , 3 ]

In [5]:
print(type(vector))

<class 'list'>


In [6]:
nvector = numpy.array(vector)

In [7]:
print(type(nvector))

<class 'numpy.ndarray'>


In [8]:
nvector.shape

(3,)

In [9]:
matrix = [
    [1 , 2 , 3],
    [ 4 , 5 , 6],
    [ 7 , 8 , 9]

]

In [10]:
print(type(matrix))

<class 'list'>


In [11]:
matrix = numpy.array(matrix)

In [12]:
matrix.shape

(3, 3)

In [ ]:
j = 3
i = [1, 2, 3]
k = [
     [1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]
]

x = [
    [[1, 2, 3] ,[4, 5, 6], [7, 8, 9 ]] ,
    [[5, 2, 3], [6, 2, 3], [8, 4, 2]] ,
    [[1, 7, 3], [6, 2, 3], [8, 4, 2]]
]

In [3]:
narr = numpy.array([1 , 2 , 3])
narr

array([1, 2, 3])

In [4]:
numpy.resize(narr , ( 4 , 4 ))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [5]:
narr.resize(( 3 , 3) , refcheck = False)

In [6]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
matrix = numpy.ones( (4  , 4 ) ) 
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
matrix = numpy.zeros(( 5 , 4 ))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
numpy.diag(narr)

array([1, 0, 0])

In [12]:
numpy.repeat([4 , 3 , 2 ] , 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [14]:
m1 = numpy.ones( (4  , 4 ) , int ) 
m1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
m2 = numpy.zeros(( 4, 4 ) , int )
m2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
numpy.vstack([m1 , m2])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
numpy.hstack([m1 , m2])

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]])

In [21]:
x = numpy.array([1 , 3, 9])
y = numpy.array([2 , 4 , 6])

In [23]:
z = x * y
z

array([ 2, 12, 54])

In [24]:
x**2

array([ 1,  9, 81])

In [25]:
x.dot(y)

np.int64(68)

In [26]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [28]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [29]:
narr.max()

np.int64(3)

In [30]:
narr.sum()

np.int64(6)

In [31]:
narr.min()

np.int64(0)

In [32]:
narr.argmax()

np.int64(2)

In [33]:
narr.argmin()

np.int64(3)

In [34]:
narr.mean()

np.float64(0.6666666666666666)

In [36]:
narr.std()

np.float64(1.0540925533894598)

In [38]:
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [39]:
mr [2]

np.int64(4)

In [40]:
mr[1 : 5]

array([ 1,  4,  9, 16])

In [41]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [42]:
mr[-2:]

array([169, 196])

In [44]:
mr[10 :: -2]

array([100,  64,  36,  16,   4,   0])

In [45]:
mr[5 : 12 : 3]

array([ 25,  64, 121])

In [46]:
mr[-10 : -2 : 2]

array([ 25,  49,  81, 121])

In [47]:
mr[-6 : 14 : 2]

array([ 81, 121, 169])

In [48]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
narr = numpy.array([
       [1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]
])

In [53]:
narr[0:2 , 1:3]

array([[2, 3],
       [0, 0]])

In [55]:
narr[::2 , -1]

array([3, 0])

In [56]:
narr[::2 , -1:]

array([[3],
       [0]])

In [57]:
narr[::-1 , 2:]

array([[0],
       [0],
       [3]])

In [59]:
narr[-2::1 , 1:3]

array([[0, 0],
       [0, 0]])

In [60]:
narr[narr>=2]

array([2, 3])

In [61]:
narr>=2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [62]:
marr = narr[-1]
marr

array([0, 0, 0])

In [63]:
marr[:] = 1
marr

array([1, 1, 1])

In [64]:
marr[:2] = 2
marr

array([2, 2, 1])

In [65]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [66]:
marr = narr.copy()
marr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [67]:
marr[:] = 0
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [68]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [70]:
tarr = numpy.random.randint(0 , 10 , (4,3))
tarr

array([[6, 2, 4],
       [8, 1, 6],
       [7, 3, 5],
       [3, 9, 3]], dtype=int32)

In [72]:
tarr[3 :: 3 , 4:1:-2]

array([[3]], dtype=int32)

In [74]:
for r in tarr :
    r = r ** 2 
    print(r)

[36  4 16]
[64  1 36]
[49  9 25]
[ 9 81  9]


In [75]:
for i , r in enumerate(tarr):
    print ('index(' + str(i) + ') is ' , r)

index(0) is  [6 2 4]
index(1) is  [8 1 6]
index(2) is  [7 3 5]
index(3) is  [3 9 3]


In [76]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [77]:
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [78]:
list(zip(narr , marr))

[(array([1, 2, 3]), array([0, 0, 0])),
 (array([0, 0, 0]), array([0, 0, 0])),
 (array([2, 2, 1]), array([0, 0, 0]))]

In [85]:
arr = [1 , 2 , 5 , 8 , 9 , 10 , 11]
arr = numpy.array(arr)
arr

array([ 1,  2,  5,  8,  9, 10, 11])

In [86]:
len(arr) // 2

3

In [87]:
p = arr [len(arr) // 2]
p

np.int64(8)

In [90]:
l = [x for x in arr if x < p]
l

[np.int64(1), np.int64(2), np.int64(5)]

In [91]:
m = [x for x in arr if x > p]
m

[np.int64(9), np.int64(10), np.int64(11)]

In [92]:
p + l + m

array([18, 20, 24])

In [93]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = numpy.array(arr)
    p = arr [len(arr) // 2]
    l = [x for x in arr if x < p]
    m =  [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [94]:
h = [5 , 10 , 1 , 13 , 9 , 4 , 3 , 0]
quicksort(h)

[np.int64(0),
 np.int64(1),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(9),
 np.int64(10),
 np.int64(13)]