In [2]:
import numpy 

In [3]:
vector = [ 1 , 2 , 3 ]

In [4]:
print(type(vector))

<class 'list'>


In [5]:
nvector = numpy.array(vector)

In [6]:
print(type(nvector))

<class 'numpy.ndarray'>


In [7]:
nvector.shape

(3,)

In [8]:
matrix = [
    [1 , 2 , 3],
    [ 4 , 5 , 6],
    [ 7 , 8 , 9]

]

In [9]:
print(type(matrix))

<class 'list'>


In [10]:
matrix = numpy.array(matrix)

In [11]:
matrix.shape

(3, 3)

In [12]:
j = 3
i = [1, 2, 3]
k = [
     [1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]
]

x = [
    [[1, 2, 3] ,[4, 5, 6], [7, 8, 9 ]] ,
    [[5, 2, 3], [6, 2, 3], [8, 4, 2]] ,
    [[1, 7, 3], [6, 2, 3], [8, 4, 2]]
]

In [13]:
narr = numpy.array([1 , 2 , 3])
narr

array([1, 2, 3])

In [14]:
numpy.resize(narr , ( 4 , 4 ))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [15]:
narr.resize(( 3 , 3) , refcheck = False)

In [16]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
matrix = numpy.ones( (4  , 4 ) ) 
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
matrix = numpy.zeros(( 5 , 4 ))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
numpy.diag(narr)

array([1, 0, 0])

In [20]:
numpy.repeat([4 , 3 , 2 ] , 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [21]:
m1 = numpy.ones( (4  , 4 ) , int ) 
m1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
m2 = numpy.zeros(( 4, 4 ) , int )
m2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
numpy.vstack([m1 , m2])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
numpy.hstack([m1 , m2])

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]])

In [25]:
x = numpy.array([1 , 3, 9])
y = numpy.array([2 , 4 , 6])

In [26]:
z = x * y
z

array([ 2, 12, 54])

In [27]:
x**2

array([ 1,  9, 81])

In [28]:
x.dot(y)

np.int64(68)

In [29]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [31]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [32]:
narr.max()

np.int64(3)

In [33]:
narr.sum()

np.int64(6)

In [34]:
narr.min()

np.int64(0)

In [35]:
narr.argmax()

np.int64(2)

In [36]:
narr.argmin()

np.int64(3)

In [37]:
narr.mean()

np.float64(0.6666666666666666)

In [38]:
narr.std()

np.float64(1.0540925533894598)

In [39]:
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [40]:
mr [2]

np.int64(4)

In [41]:
mr[1 : 5]

array([ 1,  4,  9, 16])

In [42]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [43]:
mr[-2:]

array([169, 196])

In [44]:
mr[10 :: -2]

array([100,  64,  36,  16,   4,   0])

In [45]:
mr[5 : 12 : 3]

array([ 25,  64, 121])

In [46]:
mr[-10 : -2 : 2]

array([ 25,  49,  81, 121])

In [47]:
mr[-6 : 14 : 2]

array([ 81, 121, 169])

In [48]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [49]:
narr = numpy.array([
       [1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]
])

In [50]:
narr[0:2 , 1:3]

array([[2, 3],
       [0, 0]])

In [51]:
narr[::2 , -1]

array([3, 0])

In [52]:
narr[::2 , -1:]

array([[3],
       [0]])

In [53]:
narr[::-1 , 2:]

array([[0],
       [0],
       [3]])

In [54]:
narr[-2::1 , 1:3]

array([[0, 0],
       [0, 0]])

In [55]:
narr[narr>=2]

array([2, 3])

In [56]:
narr>=2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [57]:
marr = narr[-1]
marr

array([0, 0, 0])

In [58]:
marr[:] = 1
marr

array([1, 1, 1])

In [59]:
marr[:2] = 2
marr

array([2, 2, 1])

In [60]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [61]:
marr = narr.copy()
marr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [62]:
marr[:] = 0
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [63]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [64]:
tarr = numpy.random.randint(0 , 10 , (4,3))
tarr

array([[6, 6, 0],
       [8, 7, 4],
       [6, 3, 9],
       [6, 3, 5]], dtype=int32)

In [65]:
tarr[3 :: 3 , 4:1:-2]

array([[5]], dtype=int32)

In [66]:
for r in tarr :
    r = r ** 2 
    print(r)

[36 36  0]
[64 49 16]
[36  9 81]
[36  9 25]


In [67]:
for i , r in enumerate(tarr):
    print ('index(' + str(i) + ') is ' , r)

index(0) is  [6 6 0]
index(1) is  [8 7 4]
index(2) is  [6 3 9]
index(3) is  [6 3 5]


In [68]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [69]:
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [70]:
list(zip(narr , marr))

[(array([1, 2, 3]), array([0, 0, 0])),
 (array([0, 0, 0]), array([0, 0, 0])),
 (array([2, 2, 1]), array([0, 0, 0]))]

In [71]:
arr = [1 , 2 , 5 , 8 , 9 , 10 , 11]
arr = numpy.array(arr)
arr

array([ 1,  2,  5,  8,  9, 10, 11])

In [72]:
len(arr) // 2

3

In [73]:
p = arr [len(arr) // 2]
p

np.int64(8)

In [74]:
l = [x for x in arr if x < p]
l

[np.int64(1), np.int64(2), np.int64(5)]

In [75]:
m = [x for x in arr if x > p]
m

[np.int64(9), np.int64(10), np.int64(11)]

In [76]:
p + l + m

array([18, 20, 24])

In [77]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = numpy.array(arr)
    p = arr [len(arr) // 2]
    l = [x for x in arr if x < p]
    m =  [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [78]:
h = [5 , 10 , 1 , 13 , 9 , 4 , 3 , 0]
quicksort(h)

[np.int64(0),
 np.int64(1),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(9),
 np.int64(10),
 np.int64(13)]

In [79]:
import pandas as pd

In [80]:
#data = pd.read_csv('melb_data.csv')

In [81]:
animals = ['Tiger' , 'Dog' , 'Bird']
p_animals = pd.Series(animals)
p_animals

0    Tiger
1      Dog
2     Bird
dtype: str

In [82]:
type(p_animals)

pandas.Series

In [83]:
p_animals[2]

'Bird'

In [84]:
animals = ['Tiger' , 'Dog' , None]
p_animals = pd.Series(animals)
p_animals

0    Tiger
1      Dog
2      NaN
dtype: str

In [85]:
animals = [2.0 , 20 , 1.5]
p_animals = pd.Series(animals)
p_animals

0     2.0
1    20.0
2     1.5
dtype: float64

In [86]:
animals = [2.0 , 20 ,None]
p_animals = pd.Series(animals)
p_animals

0     2.0
1    20.0
2     NaN
dtype: float64

In [87]:
animals = {
    'n1' : 'Tiger',
    'n2' : 'Dog',
    'n3' : None
}
p_animals = pd.Series(animals)
p_animals

n1    Tiger
n2      Dog
n3      NaN
dtype: str

In [88]:
print(p_animals.iloc[2])

nan


In [89]:
type(p_animals)

pandas.Series

In [90]:
p_animals.index

Index(['n1', 'n2', 'n3'], dtype='str')

In [91]:
p_animals.values

<StringArray>
['Tiger', 'Dog', nan]
Length: 3, dtype: str

In [92]:
p_animals = pd.Series(['Tiger' , 'Dog' , 'Bird'] ,index=['n1' , 'n2' , 'n3'])
p_animals

n1    Tiger
n2      Dog
n3     Bird
dtype: str

In [93]:
p_animals['n1']

'Tiger'

In [94]:
p_animals.loc['n1']

'Tiger'

In [95]:
for items in p_animals :
    print('slam' , str(items))

slam Tiger
slam Dog
slam Bird


In [96]:
animals = [21 , 22.5 , 23]
p_animals = pd.Series(animals)
numpy.sum(p_animals)

np.float64(66.5)

In [97]:
animals = [21 , 22.5 ,'Ali']
p_animals = pd.Series(animals)
p_animals

0      21
1    22.5
2     Ali
dtype: object

In [98]:
for  index, item in p_animals.items():
    print('salam' + str(item) +'...index is ' + str(index) )

salam21...index is 0
salam22.5...index is 1
salamAli...index is 2


In [99]:
animals = {
    'n1' : 'Tiger' ,
    'n2' : 'Bear' ,
    'n3' : 'Dog'
}
p_animals = pd.Series(animals)

animals = {
    'n1' : 'Tiger2' ,
    'n2' : 'Bear2' ,
    'n3' : 'Dog2'
}
p_animals2 = pd.Series(animals)
animals = {
    'n1' : 'Tiger3' ,
    'n2' : 'Bear3' ,
    'n3' : 'Dog3'
}
p_animals3 = pd.Series(animals)

df = pd.DataFrame([p_animals , p_animals2 , p_animals3 ] , index = ['r1' , 'r2' , 'r3'])
df


,n1,n2,n3
r1,Tiger,Bear,Dog
r2,Tiger2,Bear2,Dog2
r3,Tiger3,Bear3,Dog3


In [100]:
df.loc['r2']

n1    Tiger2
n2     Bear2
n3      Dog2
Name: r2, dtype: str

In [101]:
df.loc['r2'].loc['n2']

'Bear2'

In [102]:
df.loc['r1','n1']

'Tiger'

In [103]:
df.T

,r1,r2,r3
n1,Tiger,Tiger2,Tiger3
n2,Bear,Bear2,Bear3
n3,Dog,Dog2,Dog3


In [104]:
df['n2']

r1     Bear
r2    Bear2
r3    Bear3
Name: n2, dtype: str

In [105]:
df[['n2']]

,n2
r1,Bear
r2,Bear2
r3,Bear3


In [106]:
df.loc[ : , ['n1' , 'n2']]

,n1,n2
r1,Tiger,Bear
r2,Tiger2,Bear2
r3,Tiger3,Bear3


In [107]:
#df.drop('r1' , inplace = True)
df

,n1,n2,n3
r1,Tiger,Bear,Dog
r2,Tiger2,Bear2,Dog2
r3,Tiger3,Bear3,Dog3


In [108]:
df2 = df

In [109]:
df2.drop('r2' , inplace = True)

In [110]:
df2

,n1,n2,n3
r1,Tiger,Bear,Dog
r3,Tiger3,Bear3,Dog3


In [111]:
df

,n1,n2,n3
r1,Tiger,Bear,Dog
r3,Tiger3,Bear3,Dog3


In [112]:
animals = {
    'n1' : 'Tiger' ,
    'n2' : 'Bear' ,
    'n3' : 'Dog'
}
p_animals = pd.Series(animals)

animals = {
    'n1' : 'Tiger2' ,
    'n2' : 'Bear2' ,
    'n3' : 'Dog2'
}
p_animals2 = pd.Series(animals)
animals = {
    'n1' : 'Tiger3' ,
    'n2' : 'Bear3' ,
    'n3' : 'Dog3'
}
p_animals3 = pd.Series(animals)

df = pd.DataFrame([p_animals , p_animals2 , p_animals3 ] , index = ['r1' , 'r2' , 'r3'])
df


,n1,n2,n3
r1,Tiger,Bear,Dog
r2,Tiger2,Bear2,Dog2
r3,Tiger3,Bear3,Dog3


In [113]:
df3 = df[['n1' , 'n2']]
df3

,n1,n2
r1,Tiger,Bear
r2,Tiger2,Bear2
r3,Tiger3,Bear3


In [114]:
df3.drop('r1' , inplace = True)

In [119]:
df

,n1,n2,n3
r1,Tiger,Bear,Dog
r2,Tiger2,Bear2,Dog2
r3,Tiger3,Bear3,Dog3


In [116]:
df4 = df [:]
df4

,n1,n2,n3
r1,Tiger,Bear,Dog
r2,Tiger2,Bear2,Dog2
r3,Tiger3,Bear3,Dog3


In [117]:
df4.drop('r1' , inplace = True)

In [118]:
df

,n1,n2,n3
r1,Tiger,Bear,Dog
r2,Tiger2,Bear2,Dog2
r3,Tiger3,Bear3,Dog3


In [120]:
df['n1'] = 1
df

,n1,n2,n3
r1,1,Bear,Dog
r2,1,Bear2,Dog2
r3,1,Bear3,Dog3


In [122]:
df['n1'] = df['n1'] * 2
df

,n1,n2,n3
r1,2,Bear,Dog
r2,2,Bear2,Dog2
r3,2,Bear3,Dog3


In [123]:
n2 = df['n2']

In [124]:
n2 += '!' 

In [126]:
n2

r1     Bear!
r2    Bear2!
r3    Bear3!
Name: n2, dtype: str

In [127]:
df

,n1,n2,n3
r1,2,Bear,Dog
r2,2,Bear2,Dog2
r3,2,Bear3,Dog3


In [131]:
df = pd.read_csv('melb_data.csv')
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0


In [132]:
len(df)

13580

In [133]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='str')

In [138]:
df_m1000000 = df[df['Price'] > 1000000]
df_m1000000.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0
6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.8024,144.9993,Northern Metropolitan,4019.0


In [139]:
df_m1000000.tail()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0


In [140]:
df_m1000000.count()

Suburb           5743
Address          5743
Rooms            5743
Type             5743
Price            5743
Method           5743
SellerG          5743
Date             5743
Distance         5743
Postcode         5743
Bedroom2         5743
Bathroom         5743
Car              5700
Landsize         5743
BuildingArea     2979
YearBuilt        3346
CouncilArea      5049
Lattitude        5743
Longtitude       5743
Regionname       5743
Propertycount    5743
dtype: int64

In [142]:
df_m1000000['Car'].count()

np.int64(5700)

In [144]:
new_df = df[(df['Price'] > 1000000) & (df['Car'] > 1)]
new_df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
7,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,1.0,2.0,256.0,107.0,1890.0,Yarra,-37.80600,144.99540,Northern Metropolitan,4019.0
9,Abbotsford,10 Valiant St,2,h,1097000.0,S,Biggin,8/10/2016,2.5,3067.0,...,1.0,2.0,220.0,75.0,1900.0,Yarra,-37.80100,144.99890,Northern Metropolitan,4019.0
11,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12/11/2016,2.5,3067.0,...,2.0,2.0,214.0,190.0,2005.0,Yarra,-37.80850,144.99640,Northern Metropolitan,4019.0
15,Abbotsford,16 William St,2,h,1310000.0,S,Jellis,15/10/2016,2.5,3067.0,...,1.0,2.0,238.0,97.0,1890.0,Yarra,-37.80900,144.99760,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13571,Wantirna South,15 Mara Cl,4,h,1330000.0,S,Barry,26/08/2017,14.7,3152.0,...,2.0,2.0,717.0,191.0,1980.0,NaN,-37.86887,145.22116,Eastern Metropolitan,7082.0
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0


In [145]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000


In [146]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Suburb         13580 non-null  str    
 1   Address        13580 non-null  str    
 2   Rooms          13580 non-null  int64  
 3   Type           13580 non-null  str    
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  str    
 6   SellerG        13580 non-null  str    
 7   Date           13580 non-null  str    
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  str    
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13

In [147]:
new_df.sum()

Suburb           AbbotsfordAbbotsfordAbbotsfordAbbotsfordAbbots...
Address          55a Park St98 Charles St10 Valiant St40 Nichol...
Rooms                                                        13524
Type             hhhhhhuhhhthhhhhhhhhhhhhhhhhhhhhhthtuhhthhhhhh...
Price                                                 6338186257.0
Method           VBSSVBSPISSSSVBSSPISSSSPISSSSSPSSSSPSSSSSPSSSP...
SellerG          NelsonNelsonBigginNelsonJellisKayJellisNelsonB...
Date             4/06/20168/10/20168/10/201612/11/201615/10/201...
Distance                                                   37853.0
Postcode                                                11679478.0
Bedroom2                                                   13386.0
Bathroom                                                    7454.0
Car                                                         8791.0
Landsize                                                 2585798.0
BuildingArea                                           454874.

In [149]:
#new_df.mean()

In [151]:
#new_df.std()

In [152]:
#new_df.var()

In [153]:
new_df['Car'].var()

np.float64(0.6397676874973316)

In [154]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0


In [155]:
df['SA'] = df['Suburb'] + '_' + df['Address']
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,SA
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,Abbotsford_85 Turner St
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,Abbotsford_25 Bloomburg St
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,Abbotsford_5 Charles St
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,Abbotsford_40 Federation La
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0,Abbotsford_55a Park St


In [157]:
df['CARDIS'] = df['Car'] * df['Distance']
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,SA,CARDIS
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,Abbotsford_85 Turner St,2.5
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,Abbotsford_25 Bloomburg St,0.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,Abbotsford_5 Charles St,0.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,Abbotsford_40 Federation La,2.5
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0,Abbotsford_55a Park St,5.0


In [158]:
df['Type'].unique()

<StringArray>
['h', 'u', 't']
Length: 3, dtype: str

In [159]:
df['Type'].value_counts()

Type
h    9449
u    3017
t    1114
Name: count, dtype: int64

In [160]:
df.groupby('Type')['Price'].min()

Type
h    131000.0
t    300000.0
u     85000.0
Name: Price, dtype: float64

In [161]:
def f(x) :
    return x.sum() /len(x)


In [164]:
df.groupby('Type')['Price'].aggregate(f)


Type
h    1.242665e+06
t    9.337351e+05
u    6.051275e+05
Name: Price, dtype: float64

In [165]:
df.groupby('Type')['Price'].aggregate(lambda x :x.sum() /len(x) )

Type
h    1.242665e+06
t    9.337351e+05
u    6.051275e+05
Name: Price, dtype: float64